### ISSUE TITLE
Feature request: keep the cursor in view

### ISSUE THREAD

**Issue by hectorcarranza** [samu/atom-keyboard-scroll#1]
It would help to have the cursor always in hand after scrolling. 

Right now we can scroll everywhere with this plugin but when we want to type something it turns out the cursor brings us back to the place before scrolling.

PD: sorry about my not so good english.

**Comment by samu** [comment]
:+1: I agree. Not sure when i'll have time to work on it though...

**Comment by samu** [comment]
Atom now has a built in command for this: `editor:scroll-to-cursor`

**Comment by neumond** [comment]
Would be nice to have ability to scroll putting cursor in the middle of textarea. Something like `editor:scroll-to-cursor`, but putting cursor near center of screen instead top/bottom edge.
