### ISSUE TITLE
It spoils muti-line cursor keybinding

### ISSUE THREAD

**Issue by ni5ni6** [samu/atom-keyboard-scroll#2]
I use `ctrl-alt-up` and `ctrl-alt-down` to achieve multi-line editing which is in default atom keybindings.

After installing your package I cannot use them.

**Comment by samu** [comment]
This is unrelated to this plugin as this is a common problem in atom's plugin system. Its impossible to avoid keybinding clashes between different plugins. You should be able to fix this in your keymaps file.
